#POSTGRES
spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/schedule
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres

server:
  error:
    include-message: always